[package]
name = "AoC2025"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
clap = {version = "4.5.53", features = ["derive"]}
regex = "1.12.2"
nalgebra = "0.34.1"
distances = "1.8.0"